// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Display {
    /**
     * Creates a new Display instance.
     * @param {Partial<Display>} [$$source = {}] - The source object to create the Display.
     */
    constructor($$source = {}) {
        if (!("Mantissa" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Mantissa"] = "";
        }
        if (!("Exponent" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Exponent"] = "";
        }
        if (!("Sign" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Sign"] = "";
        }
        if (!("Flags" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["Flags"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Display instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Display}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Flags" in $$parsedSource) {
            $$parsedSource["Flags"] = $$createField3_0($$parsedSource["Flags"]);
        }
        return new Display(/** @type {Partial<Display>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
