// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Display {
    /**
     * Creates a new Display instance.
     * @param {Partial<Display>} [$$source = {}] - The source object to create the Display.
     */
    constructor($$source = {}) {
        if (!("mantissa" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["mantissa"] = "";
        }
        if (!("exponent" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["exponent"] = "";
        }
        if (!("sign" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["sign"] = "";
        }
        if (!("flags" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["flags"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Display instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Display}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("flags" in $$parsedSource) {
            $$parsedSource["flags"] = $$createField3_0($$parsedSource["flags"]);
        }
        return new Display(/** @type {Partial<Display>} */($$parsedSource));
    }
}

export class KeyInput {
    /**
     * Creates a new KeyInput instance.
     * @param {Partial<KeyInput>} [$$source = {}] - The source object to create the KeyInput.
     */
    constructor($$source = {}) {
        if (!("op" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["op"] = "";
        }
        if (!("arg" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["arg"] = 0;
        }
        if (!("argS" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["argS"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new KeyInput instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {KeyInput}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new KeyInput(/** @type {Partial<KeyInput>} */($$parsedSource));
    }
}

export class KeyResult {
    /**
     * Creates a new KeyResult instance.
     * @param {Partial<KeyResult>} [$$source = {}] - The source object to create the KeyResult.
     */
    constructor($$source = {}) {
        if (!("display" in $$source)) {
            /**
             * @member
             * @type {Display}
             */
            this["display"] = (new Display());
        }
        if (!("stackX" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["stackX"] = 0;
        }
        if (!("stackY" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["stackY"] = 0;
        }
        if (!("stackZ" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["stackZ"] = 0;
        }
        if (!("stackT" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["stackT"] = 0;
        }
        if (!("lastX" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["lastX"] = 0;
        }
        if (!("flags" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["flags"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new KeyResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {KeyResult}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType1;
        const $$createField6_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("display" in $$parsedSource) {
            $$parsedSource["display"] = $$createField0_0($$parsedSource["display"]);
        }
        if ("flags" in $$parsedSource) {
            $$parsedSource["flags"] = $$createField6_0($$parsedSource["flags"]);
        }
        return new KeyResult(/** @type {Partial<KeyResult>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = Display.createFrom;
